[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rirt"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]
include = ["rirt*"]

[project.scripts]
rirt = "rirt:main"
